### ISSUE TITLE
[BE] 이슈 정보 수정 기능

### ISSUE THREAD

**Issue by jsjseop** [room-number7-presents/issue-tracker-max#42]
## TODO
- [x] 이슈 제목 수정
- [x] 이슈 내용 수정
- [x] 이슈 담당자 수정
- [x] 이슈 레이블 수정
- [x] 이슈 마일스톤 수정
