### ISSUE TITLE
[FE] 이슈 추가 페이지

### ISSUE THREAD

**Issue by gunoc** [room-number7-presents/issue-tracker-max#50]
## Task
- [x] 사용자는 이슈 작성 버튼을 클릭하여 이슈 작성 페이지로 이동할 수 있다.
- [x] 담당자, 레이블, 마일스톤 등 토글 목록을 반환한다.
    - [x]  각 항목의 화살표 버튼을 누르면 해당 항목을 선택할 수 있는 팝업이 뜬다.
- [x]  이슈 목록에서 [이슈 작성]버튼을 누르면 새로운 이슈를 작성할 수 있는 페이지로 이동한다.
- [x] 새로운 이슈는 제목만 입력해도 [완료]버튼이 활성화 된다.
- [x] [완료]버튼 좌측의 [작성 취소]버튼을 누르면 아무런 변화 없이 이슈 목록으로 돌아간다.
- [x] 코멘트 영역에는 내용을 작성하다가 멈추는 경우, 현재 입력된 글자 수가 2초간 나타난 후 사라지는 기능을 구현한다.
- [x]  코멘트 영역 하단의 [파일 첨부하기]버튼을 누르면 이미지를 선택할 수 있는 창이 뜬다.
    - [x] 이미지 첨부 시에 이미지를 서버에 저장하고 이미지의 제목과 url을 반환한다.
- [x]  저장된 이미지 주소가 마크다운 형식으로 코멘트 영역에 추가된다.
- [x]  첨부 목록은 이미지만 받을 수 있게 검사한다.

## FE

- [x]  담당자, 레이블, 마일스톤 등 토글 목록을 렌더링한다.
    - [x] 레이블은 중복 선택이 가능하다.
    - [x] 담당자, 마일스톤은 중복 선택이 불가능하다. => postman api예시대로 담당자 복수선택 구현
- [x]  제목만 입력해도 완료 버튼을 활성화 시킨다.
- [x]  취소 버튼을 누르면 아무런 변화 없이 이슈 목록으로 돌아간다.
- [x]  내용 입력중에 입력된 글자수를 표시하고 내용 입력이 중단되면 2초후 글자수 안내가 사라진다. 
- [x] 파일 첨부하기 버튼을 클릭하면 이미지를 선택할 수 있는 창이 뜬다.
    - [x] 이미지 파일만으로 제한
        - [x] 첨부한 파일이 이미지 형식이 아닌 경우 2초간 `'이미지 형식만 업로드 할 수 있습니다.'` 텍스트를 파일 첨부하기 버튼 옆에 렌더링한다.
    - [x] 용량 1MB으로 제한
        - [x] 용량을 초과했을 경우 2초간 `'업로드 가능한 최대 용량은 1MB입니다.'` 텍스트를 파일 첨부하기 버튼 옆에 렌더링한다
    - [x]  이미지를 첨부하는 순간 서버에 요청을 한다.
    - [x]  업로드 중이라고 텍스트에 추가한다. `‘이미지 업로드 중...'`
    - [x]  첨부가 완료되면 추가한 텍스트를 삭제하고 업로드한 링크를 마크다운 문법으로 변환하여 텍스트로 추가한다. ⇒ 위치 일단 본문 텍스트 끝에
    - [x] 첨부가 실패한 경우 `‘업로드에 실패했습니다.’` 라고 텍스트를 파일 첨부하기 버튼 옆에 렌더링한다.
