### ISSUE TITLE
[BE] CI/CD 환경 구축

### ISSUE THREAD

**Issue by jsjseop** [room-number7-presents/issue-tracker-max#6]
## TODO
- [x] CI 스크립트 작성
- [x] EC2, RDS 생성
- [x] CD 스크립트 작성
