### ISSUE TITLE
[FE] 레이블 페이지 기능 구현

### ISSUE THREAD

**Issue by gunoc** [room-number7-presents/issue-tracker-max#93]
# 1. 레이블 조회
## Task
- [x] 이슈 목록(메인)에서 화면 우상단에 있는 [레이블] 버튼을 클릭하면 레이블 목록 화면으로 새로고침 없이 이동한다.
- [x] 좌상단의 [레이블]버튼과 [마일스톤]버튼을 통해 손쉽게 두 페이지를 번갈아 이동할 수 있다.
- [x] 레이블 목록 상단에 전체 레이블 개수가 표시되며, 각 레이블 목록에는 아래의 내용이 보여진다.
    - [x] 레이블 이름과 색
    - [x] 레이블에 대한 한 줄 설명(없을 경우 표시하지 않는다)
    - [x] [편집]버튼과 [삭제]버튼
- [ ] 레이블 목록에서 특정 레이블의 [삭제]버튼을 누르면 “정말 이 레이블을 삭제하시겠습니까?(취소/삭제)”의 알럿창이 뜬다.

## FE
- [x] 레이블 페이지를 렌더링한다.
- [x] 레이블 목록을 서버에 요청하여 리스트를 렌더링한다.
    - [x] 레이블 아이콘
    - [x] 레이블에 대한 설명
    - [x] 편집, 삭제 버튼

# 2. 레이블 추가
## Task
- [x] 우상단의 [레이블 추가]버튼을 누르면, [레이블 추가]버튼은 비활성화 되고, 새로운 레이블을 생성할 수 있는 영역이 나타난다.
    - [x] 레이블 이름(필수)
    - [x] 레이블에 대한 설명(선택사항)
    - [x] 레이블 배경 색상(필수, 직접 입력하거나, 리프레시 버튼을 눌러 랜덤 컬러를 사용할 수 있음)
        - [x] 완전 랜덤 (배경색)
        - [ ] [[글자색 관련 참고 링크](http://yoonbumtae.com/?p=2977)](http://yoonbumtae.com/?p=2977) (옵션)
    - [x] 레이블의 텍스트 색상(필수, 어두운 색/밝은 색) - 선택가능
- [x] 입력한 내용을 바탕으로 레이블을 미리보기 할 수 있고, 필수 항목이 모두 입력되면 [완료]버튼이 활성화 된다.

## FE
- [x] 레이블 추가 버튼을 누르면 새로운 레이블 추가 컴포넌트가 렌더링 된다.
- [x] 새로운 레이블 추가 컴포넌트가 렌더링 되어 있는 상태일 때, 레이블 추가 버튼이 비활성화 된다.
- [x] 배경색 초기값은 랜덤한 색상으로 먼저 주어진다.
- [x] 배경 색상 랜덤 버튼을 클릭하면 랜덤 색상 코드를 만들어 렌더링 시킨다.
- [x] 텍스트 초기값은 어두운 색으로 먼저 주어진다. → [[글자색 관련 참고 링크](http://yoonbumtae.com/?p=2977)](http://yoonbumtae.com/?p=2977) (옵션)
    - [x] 초기값은 기획서대로 "텍스트 색상"으로 변경
    - [x] 밝은 색, 어두운 색 두가지 선택지를 준다.
- [ ] 완료 버튼을 누르면 레이블 추가 요청을 한다.
- [ ] 현재: 다시 페치요청보내서 리스트를 받아오는 방식 => 페치요청 X, 리스트 상태에 추가만 해서 렌더링

# 3.레이블 편집
## Task
- [x] 레이블 목록에서 특정 레이블의 [편집]버튼을 누르면, 해당 레이블이 **편집 영역으로 전환**된다.
- [x] 레이블 편집 영역은 레이블 생성 영역과 똑같이 기능하되, [완료 → 편집 완료]버튼으로 보여진다.
- [x] [편집 완료]버튼은 레이블에 변경사항이 있을 경우에만 활성화 되도록 하고, [취소]버튼을 누르면 아무런 변경 없이 기존 레이블 목록으로 전환된다.

### FE

- [x] 편집 버튼을 누르면 해당 레이블의 리스트가 없어진다.
- [x] **새로운 레이블 추가 컴포넌트**를 재사용한다.
- [x] 타이틀은 “레이블 **편집**”, 버튼은 “편집 완료”, 버튼에 아이콘도 바뀜
- [x] 해당 레이블의 내용이 input 초기값이 된다.
    - [x] 레이블의 내용에 변화가 없을 경우 편집 완료 버튼은 비활성화 상태로 유지된다.
- [x] 취소를 눌렀을 경우 레이블 편집 컴포넌트가 사라지고 기존의 리스트 항목으로 돌아온다.
- [x] 편집 완료 버튼을 누르면 편집 요청을 보낸다.
    - [ ] 응답 200이 오면 편집된 레이블을 상태로 업데이트하고 편집 컴포넌트를 없애고 리스트로 렌더링한다.
    - [ ] 응답 200이 아닌 경우 버튼 위에 빨간 글씨로 사유와 유저에게 지시할 내용을 렌더링한다.
 # 4. 레이블 삭제
## 설명

- [ ] 삭제 버튼을 누르면 삭제할 것인지 확인하는 알럿창이 뜬다.
- [ ] 취소 버튼을 누르면 유지되고 알럿창이 닫힌다.
- [ ] 확인 버튼을 누르면 삭제되고 알럿창이 닫힌다.

### FE

- [ ] 레이블 리스트의 삭제 버튼을 클릭하면 알럿창이 뜬다.
    - [ ] 취소 버튼을 누르면 유지되고 알럿창이 닫힌다.
    - [ ] 확인 버튼을 누르면 삭제 요청을 보내고 알럿창이 닫힌다.
    - [ ] 200 응답이 오면 레이블 리스트에서 삭제 시킨다.
    - [ ] 200 응답이 아닌 경우 삭제 시키지 않는다.
        - [ ] 토스트 메시지를 띄운다.(ex. 서버와의 연결이 좋지 않습니다. 다시 시도해주세요.)(옵션)
